// <auto-generated />
using AwtadStudy.Database;
using AwtadStudy.Universities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AwtadStudy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "university", new[] { "none", "tel_aviv", "technion", "bar_ilan", "haifa" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AwtadStudy.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<University>("UniversityId")
                        .HasColumnType("university");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AwtadStudy.Users.User", b =>
                {
                    b.OwnsMany("AwtadStudy.Universities.Courses.Course", "Courses", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LectureGroupId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PracticeGroupId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Semester")
                                .HasColumnType("integer");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("Users");

                            b1.ToJson("Courses");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
